# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Professor'),
        ),
    ]
