# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('Generals', (('TEO', 'Aula teoria'), ('EXA', "Aula d'examen"))), ('Espec\xedfics', (('LAB', 'Laboratori'), ('INF', "Aula d'inform\xe0tica")))], default='TEO', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('has_count', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.Campus')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='properties',
            field=models.ManyToManyField(to='supervision.ClassroomProperties'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.Zone'),
        ),
    ]
